### ISSUE TITLE
关于压缩后的图片位置问题

### ISSUE THREAD

**Issue by qianlongo** [DDU1222/Batch-download#1]
## 图片位置

> 默认压缩后的图片位置是当前项目的images文件夹中。而且如果用户没有建images文件夹，程序会有一定的问题，如图，所以如果没有这个文件夹可能需要主动创建一个

![](http://odssgnnpf.bkt.clouddn.com/QQ20170829-124358@2x.png)

## 位置是否可配置

> 可以让压缩后的图片位置可配置吗？

**Comment by DDU1222** [comment]
已添加此功能
